--- #YAML:1.0
name:               WWW-DreamHost-API
version:            1.03
abstract:           DreamHost Web Panel API
author:
    - Serguei Trouchelle <stro@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Crypt::SSLeay:        0
    Data::UUID:           0
    LWP::Protocol::https:  0
    LWP::UserAgent:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
